GET http://localhost:3000/app
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzMzMyNzMsImV4cCI6MTczMjg2OTI3MywiYXVkIjoiNjU2ODQ5MDNiOGZjZGUwMDA4MDgyNDgwIiwiaXNzIjoidW5pb24uY29tIn0.EyFZjYWSCyUa5jijYHQ-PQxGj_zFB2qmbmH70uHDrMg

###Login Route
POST https://auth-master.vercel.app/auth/login
Content-Type: application/json

{
  "username": "ilyosbek2003",
  "password": "1234"
}


###Register Route
POST https://auth-master.vercel.app/auth/register
Content-Type: application/json

{
  "username": "ilyosbek2004",
  "password": "1234"
}